-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-12-07 18:23:11 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE angajat 
    ( 
     id_angajat NUMBER (4) , 
     cnp        NUMBER (13)  NOT NULL , 
     nume       VARCHAR2 (30)  NOT NULL , 
     prenume    VARCHAR2 (30)  NOT NULL , 
     salariu    NUMBER (4,2)  NOT NULL , 
     functie    VARCHAR2 (30)  NOT NULL , 
     email      VARCHAR2 (40) 
    ) 
;

ALTER TABLE angajat 
    ADD CONSTRAINT angajat_nume_CK 
    CHECK (length(nume)>1) 
;

ALTER TABLE angajat 
    ADD CONSTRAINT angajat_prenume_CK 
    CHECK (length(prenume)>1) 
;

ALTER TABLE angajat 
    ADD CONSTRAINT angajat_functie_CK 
    CHECK (length(functie)>1 OR functie IN ('asistent_manager', 'beauty_advisor', 'casier', 'director_general', 'manager_de_magazin', 'sef_de_raion', 'vanzator', 'visual_merchandiser')) 
;

ALTER TABLE angajat 
    ADD CONSTRAINT angajat_email_CK 
    CHECK (regexp_like(email, '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE angajat 
    ADD CONSTRAINT id_angajat_PK PRIMARY KEY ( id_angajat ) ;

ALTER TABLE angajat 
    ADD CONSTRAINT angajat_cnp_UK UNIQUE ( cnp ) ;

ALTER TABLE angajat 
    ADD CONSTRAINT angajat_email_UK UNIQUE ( email ) ;

CREATE TABLE client 
    ( 
     id_client NUMBER (5)  NOT NULL , 
     nume      VARCHAR2 (30)  NOT NULL , 
     adresa    VARCHAR2 (40) , 
     telefon   NUMBER (10) , 
     id_cont   NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE client 
    ADD CONSTRAINT client_nume_CK 
    CHECK (length(nume)>1) 
;
CREATE UNIQUE INDEX client__IDX ON client 
    ( 
     id_cont ASC 
    ) 
;

ALTER TABLE client 
    ADD CONSTRAINT id_client_PK PRIMARY KEY ( id_client ) ;

ALTER TABLE client 
    ADD CONSTRAINT client_telefon UNIQUE ( telefon ) ;

CREATE TABLE cont_in_aplicatie 
    ( 
     id_cont NUMBER (5)  NOT NULL , 
     nume    VARCHAR2 (30)  NOT NULL , 
     email   VARCHAR2 (50)  NOT NULL , 
     telefon NUMBER (10) 
    ) 
;

ALTER TABLE cont_in_aplicatie 
    ADD CONSTRAINT cont_in_aplicatie_nume_CK 
    CHECK (length(nume)>1) 
;

ALTER TABLE cont_in_aplicatie 
    ADD CONSTRAINT cont_in_aplicatie_email_CK 
    CHECK (regexp_like(email, '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}')) 
;

ALTER TABLE cont_in_aplicatie 
    ADD CONSTRAINT cont_in_aplicatie_id_cont_PK PRIMARY KEY ( id_cont ) ;

ALTER TABLE cont_in_aplicatie 
    ADD CONSTRAINT cont_in_aplicatie_email_UK UNIQUE ( email ) ;

ALTER TABLE cont_in_aplicatie 
    ADD CONSTRAINT cont_in_aplicatie_telefon_UK UNIQUE ( telefon ) ;

CREATE TABLE contract 
    ( 
     id_contract   NUMBER (4)  NOT NULL , 
     data_incepere DATE  NOT NULL , 
     data_incheiere DATE , 
     id_angajat    NUMBER (4)  NOT NULL , 
     specificatii  VARCHAR2 (30) , 
     clauze        VARCHAR2 (50) , 
     iban          VARCHAR2 (34)  NOT NULL , 
     id            NUMBER (5)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX contract__IDX ON contract 
    ( 
     id ASC 
    ) 
;

ALTER TABLE contract 
    ADD CONSTRAINT id_contract_PK PRIMARY KEY ( id_contract ) ;

CREATE TABLE factura 
    ( 
     id_factura        NUMBER (5)  NOT NULL , 
     persoana_fizica   CHAR (2) , 
     persoana_juridica CHAR (2) , 
     data              DATE , 
     valoarea          NUMBER (4)  NOT NULL , 
     id_angajat        NUMBER (4)  NOT NULL , 
     id_client         NUMBER (5)  NOT NULL 
    ) 
;

ALTER TABLE factura 
    ADD CONSTRAINT factura_persoana_fizica 
    CHECK (persoana_fizica IN ('Da', 'Nu')) 
;

ALTER TABLE factura 
    ADD 
    CHECK (persoana_juridica IN ('Da', 'Nu')) 
;

ALTER TABLE factura 
    ADD CONSTRAINT id_factura_PK PRIMARY KEY ( id_factura ) ;

CREATE TABLE furnizor 
    ( 
     iban    VARCHAR2 (34)  NOT NULL , 
     nume    VARCHAR2 (50)  NOT NULL , 
     telefon NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE furnizor 
    ADD CONSTRAINT furnizor_nume_CK 
    CHECK (length(nume)>1) 
;

ALTER TABLE furnizor 
    ADD CONSTRAINT furnizor_iban_PK PRIMARY KEY ( iban ) ;

ALTER TABLE furnizor 
    ADD CONSTRAINT furnizor_nume_UK UNIQUE ( nume ) ;

ALTER TABLE furnizor 
    ADD CONSTRAINT furnizor_telefon_UK UNIQUE ( telefon ) ;

CREATE TABLE inregistrare 
    ( 
     id          NUMBER (5)  NOT NULL , 
     id_produs   NUMBER (6)  NOT NULL , 
     id_angajat  NUMBER (4)  NOT NULL , 
     id_contract NUMBER (4)  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX inregistrare__IDX ON inregistrare 
    ( 
     id_contract ASC 
    ) 
;

ALTER TABLE inregistrare 
    ADD CONSTRAINT inregistrare_PK PRIMARY KEY ( id ) ;

CREATE TABLE produs 
    ( 
     id_produs     NUMBER (6)  NOT NULL , 
     denumire      VARCHAR2 (60)  NOT NULL , 
     brand         VARCHAR2 (30)  NOT NULL , 
     stoc          NUMBER (6) , 
     tip_produs    VARCHAR2 (50)  NOT NULL , 
     pret          NUMBER (3)  NOT NULL , 
     data_expirare DATE  NOT NULL 
    ) 
;

ALTER TABLE produs 
    ADD CONSTRAINT produs_denumire_CK 
    CHECK (length(denumire)>1) 
;

ALTER TABLE produs 
    ADD CONSTRAINT produs_brand_CK 
    CHECK (length(brand)>1) 
;

ALTER TABLE produs 
    ADD CONSTRAINT produs_stoc 
    CHECK (stoc>0) 
;

ALTER TABLE produs 
    ADD CONSTRAINT produs_tip_produs_CK 
    CHECK (length(tip_produs)>1) 
;

ALTER TABLE produs 
    ADD CONSTRAINT produs_pret_CK 
    CHECK (pret BETWEEN 10 AND 3000) 
;

ALTER TABLE produs 
    ADD CONSTRAINT id_prdous_PK PRIMARY KEY ( id_produs ) ;

ALTER TABLE produs 
    ADD CONSTRAINT produs_brand_UK UNIQUE ( brand ) ;

ALTER TABLE contract 
    ADD CONSTRAINT angajat_contract_fk FOREIGN KEY 
    ( 
     id_angajat
    ) 
    REFERENCES angajat 
    ( 
     id_angajat
    ) 
;

ALTER TABLE factura 
    ADD CONSTRAINT angajat_factura_fk FOREIGN KEY 
    ( 
     id_angajat
    ) 
    REFERENCES angajat 
    ( 
     id_angajat
    ) 
;

ALTER TABLE inregistrare 
    ADD CONSTRAINT angajat_inregistrare_fk FOREIGN KEY 
    ( 
     id_angajat
    ) 
    REFERENCES angajat 
    ( 
     id_angajat
    ) 
;

ALTER TABLE client 
    ADD CONSTRAINT cleint_cont_in_aplicatie_fk FOREIGN KEY 
    ( 
     id_cont
    ) 
    REFERENCES cont_in_aplicatie 
    ( 
     id_cont
    ) 
;

ALTER TABLE factura 
    ADD CONSTRAINT client_factura_fk FOREIGN KEY 
    ( 
     id_client
    ) 
    REFERENCES client 
    ( 
     id_client
    ) 
;

ALTER TABLE contract 
    ADD CONSTRAINT furnizor_contract_fk FOREIGN KEY 
    ( 
     iban
    ) 
    REFERENCES furnizor 
    ( 
     iban
    ) 
;

ALTER TABLE inregistrare 
    ADD CONSTRAINT produs_angajat_fk FOREIGN KEY 
    ( 
     id_produs
    ) 
    REFERENCES produs 
    ( 
     id_produs
    ) 
;

CREATE SEQUENCE angajat_id_angajat_SEQ 
START WITH 250 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER angajat_id_angajat_TRG 
BEFORE INSERT ON angajat 
FOR EACH ROW 
WHEN (NEW.id_angajat IS NULL) 
BEGIN 
    :NEW.id_angajat := angajat_id_angajat_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE client_id_client_SEQ 
START WITH 130 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER client_id_client_TRG 
BEFORE INSERT ON client 
FOR EACH ROW 
WHEN (NEW.id_client IS NULL) 
BEGIN 
    :NEW.id_client := client_id_client_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE cont_in_aplicatie_id_cont_SEQ 
START WITH 550 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER cont_in_aplicatie_id_cont_TRG 
BEFORE INSERT ON cont_in_aplicatie 
FOR EACH ROW 
WHEN (NEW.id_cont IS NULL) 
BEGIN 
    :NEW.id_cont := cont_in_aplicatie_id_cont_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE contract_id_contract_SEQ 
START WITH 100 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER contract_id_contract_TRG 
BEFORE INSERT ON contract 
FOR EACH ROW 
WHEN (NEW.id_contract IS NULL) 
BEGIN 
    :NEW.id_contract := contract_id_contract_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE factura_id_factura_SEQ 
START WITH 420 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER factura_id_factura_TRG 
BEFORE INSERT ON factura 
FOR EACH ROW 
WHEN (NEW.id_factura IS NULL) 
BEGIN 
    :NEW.id_factura := factura_id_factura_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE inregistrare_id_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER inregistrare_id_TRG 
BEFORE INSERT ON inregistrare 
FOR EACH ROW 
WHEN (NEW.id IS NULL) 
BEGIN 
    :NEW.id := inregistrare_id_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE produs_id_produs_SEQ 
START WITH 820 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER produs_id_produs_TRG 
BEFORE INSERT ON produs 
FOR EACH ROW 
WHEN (NEW.id_produs IS NULL) 
BEGIN 
    :NEW.id_produs := produs_id_produs_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             3
-- ALTER TABLE                             38
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
